# Generated by Django 2.2.11 on 2020-03-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('arrival', models.DateTimeField()),
                ('departure', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('no_of_people', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
