# Generated by Django 2.2.11 on 2020-03-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='arrival',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='departure',
            field=models.DateField(),
        ),
    ]
